### ISSUE TITLE
Literally no way to use this

### ISSUE THREAD

**Issue by shalins** [Giphy/giphy-ios-sdk-ui-example#4] opened 2019-07-14 06:46 UTC
This is literally the worst repo of all time. I can't stress enough how stupid these developers must be to release a repo that they claim works but literally doesn't. First of all, you have to manually run pod install every time. Also I've installed like 5 different versions of Xcode including version 10.1, 10.2 and 11 beta 3. None of the Xcode versions work with this stupid repo. Jesus Christ fix the fucking thing guys.

**Comment by cgmaier** [comment] 2019-07-16 18:59
Hey there, thanks for checking out the SDK. Sorry to hear you’re having trouble. We'd love to help. 

Are you having trouble running the example project on your machine, or just using the Giphy pod in another project? If it is another project, is that project based in Objective-c or Swift? 

In the case that the problem is with running the example, are you trying to run the Swift or Objective-C example project?

Are you encountering any specific compilation or runtime errors?

**Comment by cgmaier** [comment] 2019-07-19 14:28
I'm going to close this. Please reopen a new issue if you can better isolate your problem

**Closed by cgmaier** 2019-07-19 14:28 UTC
