### ISSUE TITLE
Build error in Xcode12

### ISSUE THREAD

**Issue by Lottikeres** [Giphy/giphy-ios-sdk-ui-example#77] opened 2020-07-08 01:21 UTC
Help, when I compile giphy on xcode12, it prompts "may have used features that aren't supported by this compiler". Is there any configuration that I need to change? Or need to wait for you to update the sdk？
![image](https://user-images.githubusercontent.com/26219862/86861425-a7a1a600-c0f9-11ea-96a8-10b87cc9aee0.png)

**Comment by cgmaier** [comment] 2020-07-08 17:16
thanks for flagging this @Lottikeres ! will get back to you soon.

**Comment by cgmaier** [comment] 2020-07-09 20:42
hey @Lottikeres - just built a test app with the latest version of the GIPHY SDK as a dependency and was able to run it fine with out any errors. can you please confirm your SDK version / whether you are using Cocoapods or Carthage?

**Comment by Lottikeres** [comment] 2020-07-10 01:26
Thanks @cgmaier  for your reply, I just created a demo and run it, this problem still occurs.Below is some of my environmental information, pls help me see where the problem is.
```
Xcode Version: 12.0 beta 2 (12A6163b)
Cocoapods Version: 1.7.5
Giphy: 1.2.9
```
The content in the podfile is like this:

```
platform :ios, "11.0"
#inhibit_all_warnings!
use_modular_headers!
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
    installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
    end
end

def app_pods
    pod 'Giphy', '~> 1.2.9'
end

target 'GiphyDemo' do
    app_pods
end
```

**Comment by cgmaier** [comment] 2020-07-10 13:19
thanks for the details @Lottikeres - will get back to u soon : )

**Comment by cgmaier** [comment] 2020-07-10 14:49
hey @Lottikeres i was able to reproduce your issue. it's necessary to add the 
`use_frameworks!` flag - when I removed the flag I encountered the same compilation error as you. i'll better highlight this requirement in the documentation. thanks! 

```
use_frameworks!

target "YourAppTarget" do 
pod 'Giphy' 
end
```

**Comment by Lottikeres** [comment] 2020-07-13 12:24
hey @cgmaier, when I add the `use_frameworks!`, this error is gone, but another error was encountered. I guess it may be a problem caused by Cocoapods, can you tell me what your Cocoapods version ?
![image](https://user-images.githubusercontent.com/26219862/87303944-949e3400-c546-11ea-9737-8c9d151364b8.png)

**Comment by cgmaier** [comment] 2020-07-13 12:47
hi @Lottikeres - I'm on the latest release of Cocoapods, `1.9.2`. Is there any reason why you can't upgrade your CocoaPods version?

I also recommend clearing derived data / cleaning / closing and reopening Xcode just to be sure it's not some weird Xcode state thing : )

**Comment by ankush-bhatia** [comment] 2020-07-17 20:56
Hi, @cgmaier I am also facing the same issue. Tried all the solutions mentioned above.

XCode - 12.0 - beta 2
Cocoapods Version: 1.9.3

I think the framework needs to be rebuilt from compiler supporting Swift 5.3. 
Thanks.

**Comment by cgmaier** [comment] 2020-07-18 13:53
thanks for confirming @ankush-bhatia 
 
there must be something unique about my environment. I'll look into it and get back to you soon

**Comment by cgmaier** [comment] 2020-07-20 15:37
hey @ankush-bhatia and @Lottikeres - i'm still unable to reproduce on my end unfortunately. I've asked a teammate to try on their machine

can either of you confirm whether this issue is reproducible in the swift example app? thanks !

**Comment by cgmaier** [comment] 2020-07-20 16:10
well this is interesting! 

https://www.youtube.com/watch?v=d0fN3iOIVg8

it appears that adjusting the iOS version in the Deployment Info has an effect. 

if the version is above 13.3, the error happens, otherwise the build is fine.   

cc @ankush-bhatia @Lottikeres

**Comment by ankush-bhatia** [comment] 2020-07-22 04:48
Yes, that is true. Changing the iOS version above 13.3 causes the issue. That is why from the error description I feel that the framework needs to be rebuilt for Swift 5.3 @cgmaier

**Comment by ankush-bhatia** [comment] 2020-08-03 06:01
Hi @cgmaier 

Just wanted to know if there is any update on this issue.

Thanks.

**Comment by cgmaier** [comment] 2020-08-04 14:05
It's not a matter of rebuilding for Swift 5.3. The GIPHY SDK supports all Swift versions since Swift 5.1. This can be verified in Xcode 11.6.

It appears that this is a known issue with the Xcode Beta: https://developer.apple.com/forums/thread/649918

**Closed** 2020-08-11 20:21 UTC
