### ISSUE TITLE
Crash in PingbackCollector

### ISSUE THREAD

**Issue by johnlo-bandlab** [Giphy/giphy-ios-sdk-ui-example#81] opened 2020-07-28 03:18 UTC
We have very few crash of this nature. I'm not sure if we cause this because it only started appearing a couple of weeks ago after months of using giphy.

<img width="875" alt="Screen Shot 2020-07-28 at 11 10 37 AM" src="https://user-images.githubusercontent.com/52393419/88615130-e48f0600-d0c3-11ea-8833-0d5a83ba7205.png">

**Comment by cgmaier** [comment] 2020-07-30 20:34
we dogfood the sdk in our GIPHY apps, and haven't identified any similar crashes. it could be a red herring?

**Comment by beamPacer** [comment] 2020-08-11 16:26
Hey Chris! We've seen this same issue in TextNow -- here's a similar screenshot from Fabric. I came here to report it and see that there's already this thread! Yay. Let us know if you need more information.

<img width="725" alt="giphy crash" src="https://user-images.githubusercontent.com/1409593/89922967-b0800e80-dbb4-11ea-88c7-61172943710b.png">

**Comment by beamPacer** [comment] 2020-08-11 16:37
I looked at our metrics and it appears that there's a 10:1 ratio between the number of users who successfully sent a gif from Giphy to the number of crashes we're seeing with this signature. Those numbers are only _mostly_ correlated, of course.

**Comment by cgmaier** [comment] 2020-08-11 20:21
hopeful fix for the latest release: 

https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.0

has anyone been able to reproduce or gotten any outreach from users that verify this not ? 10:1 seems like a fairly significant ratio, considering we can't seem to reproduce it ourselves.

**Comment by beamPacer** [comment] 2020-08-11 22:48
We're working on reproducing it in-house and will let you know -- thanks as always for the quick response! I'm wondering if it happens on initialize -- if so it would look the same as any other crash to our users, and the ratio of _all_ of our users to the number of crashes with this signature is significantly lower than 10:1.

**Comment by johnlo-bandlab** [comment] 2020-08-12 02:21
We started encountering this crash when we move things around in our project resulting on us calling `Giphy.configure(apiKey: "ourkey")` everytime we open our chat feature.

**Comment by cgmaier** [comment] 2020-08-12 05:00
hi @johnlo-bandlab ! that's interesting - did only calling 'configure' once fix the issue? 

if not, do know happen to know if the crash also may have also corresponded to an update in the GIPHY SDK version? 

thanks for your help @johnlo-bandlab & @beamPacer

**Comment by cgmaier** [comment] 2020-08-24 21:40
an update here: as @johnlo-bandlab has suggested, this crash seems to result from multiple calls to `Giphy.configure(apiKey: "apiKey")`. 

I did a deep dive in the code today and found that `configure` ends up creating a new serial dispatch queue every time it is called, and loses the reference to any previously active queue as a result. 

we have a seemingly innocuous line in that `configure` function which does something like `PingbackCollector.apiKey = apiKey`. it wasn't apparent to me that `apiKey` is a computed var, and so its setter goes and does a bunch of stuff, including allocate that new dispatch queue...

we weren't able to find any crashes similar to this in the GIPHY iOS App, which "dogfoods" this SDK and only ever calls `configure` once in the app life cycle. 

we'll be sure to prevent multiple `configure` calls from causing any issues in a future release, but in the meantime, ensure `configure` is only ever called once in a given app lifecycle. also avoid using the `GiphyViewController` method `setAPIKey` for now. 

thanks all for the patience on this! cc @beamPacer

**Comment by beamPacer** [comment] 2020-08-24 22:20
Mm, ok -- thinking about this more, our static once call to configure would still be called every time a new instance of the class is initialized, which explains why instances of this crash went _down_ but stayed around after we made that change. Ok! We'll go in and verify that it only ever happens exactly once no matter what.

**Comment by johnlo-bandlab** [comment] 2020-08-25 00:12
@cgmaier , Our app just got release 3 days ago so I can't fully verify yet that it fixed the issue. So far there's no instance of crash when we call configure only once. thanks for all the help. 👍

**Comment by beamPacer** [comment] 2020-09-03 18:26
We haven't seen this crash occur in our release which only calls configure once. Thanks again Chris!

**Comment by cgmaier** [comment] 2020-09-03 18:54
that's awesome! thanks for the follow up. will close this issue : )

**Closed by cgmaier** 2020-09-03 18:54 UTC

**Comment by mmdock** [comment] 2020-09-03 19:54
> we'll be sure to prevent multiple `configure` calls from causing any issues in a future release, but in the meantime, ensure `configure` is only ever called once in a given app lifecycle. also avoid using the `GiphyViewController` method `setAPIKey` for now.
> 

@cgmaier 

quick question, you write "we'll be sure to prevent multiple configure calls from causing any issues in a future release, but in the meantime, ensure configure is only ever called once in a given app lifecycle. also avoid using the GiphyViewController method setAPIKey for now."  However, I have seen no new version that actually fixes this, the solution seems to be that end developers should just not call it multiple times.  So, in my code implementation, I do call setAPIKey for each instance of GiphyViewController .  Am I right to assume that the issue is that i shouldn't call setAPIKey multiple times for the same instance, or should I just not use it altogether?

code implementation below, currently in a beta release of my application:
<img width="808" alt="Screen Shot 2020-09-03 at 12 12 18 PM" src="https://user-images.githubusercontent.com/2423465/92160802-73d6ba00-ede4-11ea-8077-26760ace16de.png">

**Comment by cgmaier** [comment] 2020-09-03 21:38
hey @mmdock with the latest release `2.0.2`, multiple calls to `configure` or `setAPIKey` won't cause issues
