### ISSUE TITLE
Swift Compiler Errors with 1.2.5 update

### ISSUE THREAD

**Issue by h36ahmed** [Giphy/giphy-ios-sdk-ui-example#60] opened 2020-04-03 21:06 UTC
![image](https://user-images.githubusercontent.com/13081913/78404837-ab182380-7618-11ea-9705-1d38cd8b8427.png)

My XCode version: 11.3.1
Swift version: 5.1.3

**Comment by dataman17** [comment] 2020-04-07 03:50
Having the same issue, which version of the SDK should I revert to?

**Comment by Kamajabu** [comment] 2020-04-07 13:25
1.2.4 seems to work; just need to also comment out one line from an example project:
```//            case .recents: button.setTitle("Recents", for: .normal)```

**Comment by cgmaier** [comment] 2020-04-07 17:04
hey all im unfortunately unable to reproduce on xcode 11.4 - are you unable to update? 

 @Kamajabu and @dataman17 - are you also on xcode 11.3?

**Comment by Kamajabu** [comment] 2020-04-07 17:21
@cgmaier yep, xcode 11.3.1.

**Comment by dataman17** [comment] 2020-04-07 22:00
Same same 11.3.1

**Comment by Reena1993** [comment] 2020-04-14 09:48
I'm also facing same this issue with xCode 11.3.1
![Screenshot 2020-04-14 at 15 17 48](https://user-images.githubusercontent.com/51085949/79210899-1eb10080-7e63-11ea-8b94-33490ef3263c.png)

**Comment by cgmaier** [comment] 2020-04-23 16:54
hey guys, sorry about the delay on this. I just pushed a release which supports 11.1 through the latest Xcode. let me know if it solves this issue

https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v1.2.6

**Comment by cgmaier** [comment] 2020-04-29 17:38
hi @dataman17 @Reena1993 @Kamajabu @h36ahmed thanks again for flagging this issue. wanted to follow up here and ask if the latest release `1.2.6` works for you in Xcode 11.3.

**Comment by cgmaier** [comment] 2020-05-05 18:34
this should be fixed once and for all with release 1.2.7 - thanks for your patience 

weird that 1.2.6 supported 11.1 and 11.4 _but not 11.3_. it appears i have to have 40 gigs of Xcode on my machine to test this in the future haha 

anyway, please let me know if this is fixed! 

cc @dataman17 @Kamajabu @h36ahmed

**Closed** 2020-05-06 13:53 UTC
